added resizing functionality to the area rects
valeriegc/image_map_creator pull request #4
Opened 2023-05-04 11:17 UTC by valeriegc

2023-05-04 11:22 UTC, kolberg-dev requested changes

2023-05-04 11:22 UTC, AlexanderKolberg commented on src/routes/Canvas.svelte
> +
What is this?

2023-05-04 11:22 UTC, AlexanderKolberg commented on src/actions/Resize.ts
> +		element.style.height = `${firstRect.height + delta}px`;
```suggestion
		const deltaX = firstPosition.x - event.pageX;
		element.style.width = `${firstRect.width - deltaX}px`;
		
		const deltaY = event.pageY - firstPosition.y;
		element.style.height = `${firstRect.height + deltaY}px`;
```

2023-05-04 11:22 UTC, AlexanderKolberg commented on src/actions/Resize.ts
> +	function onMouseup() {
```suggestion

	function onMouseup() {
```

2023-05-04 11:22 UTC, kolberg-dev commented on src/actions/Resize.ts
> +export function resizeArea(element) {
The whole file looks like its missing types?

2023-05-07 10:19 UTC, valeriegc commented on src/routes/Canvas.svelte
> +
removed

2023-05-07 10:23 UTC, valeriegc commented on src/actions/Resize.ts
> +		element.style.height = `${firstRect.height + delta}px`;
thanks! fixed.

2023-05-07 11:10 UTC, valeriegc commented on src/actions/Resize.ts
> +	function onMouseup() {
according to your words "i think i am too pedantic"

2023-05-07 12:10 UTC, kolberg-dev commented on src/routes/Canvas.svelte
> +					use:resizeArea={$mapObjects}
Why are you feeding the mapsObjects?

2023-05-07 12:18 UTC, kolberg-dev approved these changes

2023-05-07 12:18 UTC, merged